import { Project } from './types';

export const projects: Project[] = [
  {
    id: 1,
    slug: 'syncseo',
    name: 'SyncSEO',
    url: 'https://syncseo.io/',
    location: 'USA',
    locationDetail: 'IDER Internal Product',
    type: 'SaaS Platform',
    filterTypes: ['SaaS Platform', 'Web Application'],
    techStack: ['Custom SaaS Web Application'],
    isFeatured: true,
    isInternalProject: true,
    screenshotsFolder: 'syncseo.io',
    shortDescription: 'Visual content architecture platform and real-time SEO writing dashboard for SEO professionals.',
    fullDescription: `SyncSEO.io is a visual content architecture platform and real-time SEO writing dashboard developed by IDER Solutions. It assists SEO professionals and content creators in managing complex content structures and building topical authority.

The platform provides comprehensive tools for content mapping, real-time optimization feedback, and strategic internal linking suggestions to help users build authoritative content clusters.`,
    keyFeatures: [
      'Visual content mapping',
      'Interactive writing dashboard',
      'Dynamic internal linking suggestions',
      'Topical authority building tools',
      'Real-time SEO optimization feedback',
    ],
    servicesDelivered: [
      'Full SaaS product development',
      'Web application architecture',
      'Ongoing feature development and improvements',
    ],
  },
  {
    id: 2,
    slug: 'founderspath',
    name: 'Founders Path',
    url: 'https://founderspath.lk/',
    location: 'Sri Lanka',
    type: 'Web Application',
    filterTypes: ['Web Application', 'Community Platform'],
    techStack: ['Custom Web Application'],
    isFeatured: true,
    screenshotsFolder: 'founderspath.lk',
    shortDescription: 'Structured startup education and community platform helping entrepreneurs develop scalable ventures.',
    fullDescription: `FoundersPath is a structured startup education and community initiative in Sri Lanka, launched in 2025 to help entrepreneurs develop scalable ventures. It provides resources, mentorship, and a "Founder's Blueprint" roadmap covering stages from ideation to growth.

The platform serves as a comprehensive hub for startup founders to connect, share updates, and access educational resources tailored to the Sri Lankan entrepreneurial ecosystem.`,
    keyFeatures: [
      'Founder directory with searchable profiles',
      'Twitter-style founder feed for sharing growth updates',
      'Individual founder backend profiles (edit details, ventures, etc.)',
      'Super admin functionality for platform administrators',
      'Post reactions and comments system',
      'Individual founder profile pages that rank on Google',
    ],
    servicesDelivered: [
      'Full-scale custom web application development',
      'User authentication and profile management',
      'Social feed functionality',
      'Admin dashboard development',
      'SEO-optimized founder profiles',
    ],
  },
  {
    id: 3,
    slug: 'mygolfessentials',
    name: 'My Golf Essentials',
    url: 'https://mygolfessentials.com/',
    location: 'USA',
    type: 'Community Platform',
    filterTypes: ['Community Platform'],
    techStack: ['Custom Development', 'CMS Integration'],
    isFeatured: true,
    screenshotsFolder: 'mygolfessentials.com',
    shortDescription: 'Comprehensive online community and resource platform for golfers with gear guides and wellness tips.',
    fullDescription: `MyGolfEssentials.com is a comprehensive online community and resource platform designed to improve golfers' performance on and off the course. It serves as a central hub for gear recommendations, health and wellness tips, and industry news.

The platform brings together golf enthusiasts through curated content, expert articles, and a searchable directory of resources including coaches, stores, and destinations.`,
    keyFeatures: [
      'Health and Nutrition section with fitness programs and expert articles',
      'Gear and Technology guides with curated reviews',
      'Golf Directory (searchable resource center for coaches, stores, destinations)',
      'News and Community section for tournament updates and discussions',
    ],
    servicesDelivered: [
      'Full website design and development',
      'Brand identity and design system',
      'Social media management',
      'Full-scale SEO optimization',
    ],
  },
  {
    id: 4,
    slug: 'mygolfessentials-shop',
    name: 'My Golf Essentials Shop',
    url: 'https://shop.mygolfessentials.com/',
    location: 'USA',
    type: 'E-Commerce',
    filterTypes: ['E-Commerce'],
    techStack: ['Shopify'],
    isFeatured: false,
    screenshotsFolder: 'shop.mygolfessentials.com',
    shortDescription: 'E-commerce store selling premium performance supplements designed for golfers and athletes.',
    fullDescription: `The official e-commerce store for My Health Essentials, selling premium performance supplements specifically designed for golfers and athletes. Products include Elite Greens Superfood, Elite Reds Superfood, Pure Creatine, and bundled health stacks.

The store is built on Shopify with a focus on conversion optimization and seamless integration with the main My Golf Essentials website.`,
    keyFeatures: [
      'Shopify-powered storefront',
      'Product bundles and stacks',
      'Subscription-friendly product structure',
      'Seamless integration with main MGE website',
    ],
    servicesDelivered: [
      'Full Shopify development',
      'E-commerce UX optimization',
      'SEO optimization',
      'Product photography integration',
    ],
  },
  {
    id: 5,
    slug: 'tracisandersonartist',
    name: 'Traci Sanderson Artist',
    url: 'https://tracisandersonartist.com/',
    location: 'USA',
    locationDetail: 'Yountville, California',
    type: 'E-Commerce',
    filterTypes: ['E-Commerce'],
    techStack: ['Custom Code', 'Shopify (Backend)'],
    isFeatured: true,
    screenshotsFolder: 'tracisandersonartist.com',
    shortDescription: 'Digital gallery and storefront for multidisciplinary fine artist featuring original artwork and commissions.',
    fullDescription: `The official website for multidisciplinary fine artist Traci Sanderson. Functions as a digital gallery and storefront featuring original artwork, custom commissions, studio visits, and art advisory services.

The site combines a fully custom-coded frontend with premium gallery aesthetics and a Shopify backend for seamless order and payment handling.`,
    keyFeatures: [
      'Fully custom-coded frontend with premium gallery aesthetic',
      'Shopify backend for order and payment handling',
      'Clean, minimal design befitting fine art presentation',
      'Custom commission request system',
      'Studio visit booking functionality',
    ],
    servicesDelivered: [
      'Custom e-commerce solution development',
      'Gallery-style UI/UX design',
      'Shopify backend integration',
      'Art-focused visual presentation',
    ],
  },
  {
    id: 6,
    slug: 'jwmarketingco',
    name: 'JW Marketing Co',
    url: 'https://jwmarketingco.com/',
    location: 'USA',
    locationDetail: 'Napa, California',
    type: 'Corporate Website',
    filterTypes: ['Corporate Website'],
    techStack: ['Custom Code', 'WordPress (Headless CMS)'],
    isFeatured: false,
    screenshotsFolder: 'jwmarketingco.com',
    shortDescription: 'Digital marketing agency website with headless CMS architecture and automatic blog synchronization.',
    fullDescription: `JW Marketing Co is a digital marketing agency in Napa, California specializing in helping brands improve their online presence using data-driven strategies. They offer web design, social media management, digital advertising, content creation, and photography services.

The website features a headless CMS architecture with WordPress backend for blog management and a custom coded frontend for optimal performance.`,
    keyFeatures: [
      'Headless CMS architecture (WordPress backend for blog, custom coded frontend)',
      'Automatic blog synchronization between WordPress and custom site',
      'Clean, modern agency aesthetic',
      'Service showcase with case studies',
    ],
    servicesDelivered: [
      'Full-scale custom web development',
      'Headless CMS implementation',
      'Short-term digital marketing support',
      'Knowledge transfer for client takeover',
    ],
  },
  {
    id: 7,
    slug: 'riverfrontnapa',
    name: 'The Riverfront Napa',
    url: 'http://riverfrontnapa.com/',
    location: 'USA',
    locationDetail: 'Napa, California',
    type: 'Corporate Website',
    filterTypes: ['Corporate Website'],
    techStack: ['WordPress', 'Elementor', 'Custom Code'],
    isFeatured: false,
    screenshotsFolder: 'riverfrontnapa.com',
    shortDescription: 'Official website for downtown Napa commercial district featuring dining, shopping, and entertainment.',
    fullDescription: `Official website for The Riverfront in downtown Napa, California. The development blends the historic Napa Mill with modern architecture to offer dining, shopping, and entertainment.

The site guides visitors to restaurants like Morimoto Napa and Los Agaves, shops, and highlights attractions including the riverwalk and art installations.`,
    keyFeatures: [
      'Interactive tenant directory',
      'Restaurant and shop listings',
      'Event and attraction highlights',
      'Location and parking information',
      'Riverwalk and art installation features',
    ],
    servicesDelivered: [
      'Full WordPress development',
      'Elementor implementation with custom coding',
      'SEO optimization',
      'Multi-tenant directory system',
    ],
  },
  {
    id: 8,
    slug: 'chefrafaelmolina',
    name: 'Chef Rafael Molina',
    url: 'https://chefrafaelmolina.com/',
    location: 'USA',
    locationDetail: 'Napa Valley',
    type: 'Service Website',
    filterTypes: ['Service Website'],
    techStack: ['WordPress', 'Elementor', 'Custom Code'],
    isFeatured: false,
    screenshotsFolder: 'chefrafaelmolina.com',
    shortDescription: 'Professional website for Napa Valley chef specializing in French-Mexican fusion and private dining.',
    fullDescription: `Professional website for Napa Valley-based culinary professional Chef Rafael Molina, specializing in elevated French-Mexican fusion and private dining experiences.

The site features private chef services, artisanal baked goods, weekly meal prep options, and a culinary blog showcasing the chef's expertise and culinary journey.`,
    keyFeatures: [
      'Service booking functionality',
      'Menu and service showcase',
      'Culinary blog section',
      'Visual food photography integration',
    ],
    servicesDelivered: [
      'Full WordPress development',
      'Elementor implementation with custom coding',
      'SEO optimization',
      'Content structure for culinary blog',
    ],
  },
  {
    id: 9,
    slug: 'artermite',
    name: 'A&R Termite Control',
    url: 'https://artermite.com/',
    location: 'USA',
    locationDetail: 'San Mateo & Santa Clara Counties',
    type: 'Service Website',
    filterTypes: ['Service Website', 'Corporate Website'],
    techStack: ['WordPress', 'Elementor', 'Custom Code'],
    isFeatured: false,
    screenshotsFolder: 'artermite.com',
    shortDescription: 'Family-owned termite control company website with service booking and local SEO optimization.',
    fullDescription: `Website for A&R Termite Control, a family-owned company providing termite inspection, remediation, structural repairs, and maintenance services since 1976.

Services include detailed assessments for homeowners and real estate transactions, targeted treatments, and preventive solutions. The site emphasizes their 40+ years of experience and local expertise.`,
    keyFeatures: [
      'Service area focused design',
      'Real estate transaction support information',
      'Service request forms',
      'Trust signals (40+ years in business)',
    ],
    servicesDelivered: [
      'Full WordPress development',
      'Elementor implementation with custom coding',
      'Full-scale SEO optimization',
      'Local business schema markup',
    ],
  },
  {
    id: 10,
    slug: 'dec-lk',
    name: 'Dias Engineering & Construction',
    url: 'https://dec.lk/',
    location: 'Sri Lanka',
    type: 'Corporate Website',
    filterTypes: ['Corporate Website'],
    techStack: ['Custom Development'],
    isFeatured: false,
    screenshotsFolder: 'dec.lk',
    shortDescription: 'Corporate website for reputed Sri Lankan construction company showcasing services and projects.',
    fullDescription: `Company website for Dias Engineering & Construction, a reputed Sri Lankan construction company. The site showcases their services and serves as a contact point for potential clients.

The website presents the company's profile, history, and project portfolio in a professional manner suited to the construction industry.`,
    keyFeatures: [
      'Service showcase',
      'Company profile and history',
      'Project portfolio display',
      'Contact and inquiry forms',
    ],
    servicesDelivered: [
      'Full website development',
      'Service presentation design',
      'Contact system implementation',
    ],
  },
  {
    id: 11,
    slug: 'yasas-dev',
    name: 'Yasas.dev',
    url: 'https://yasas.dev/',
    location: 'Italy',
    type: 'Corporate Website',
    filterTypes: ['Corporate Website'],
    techStack: ['Custom Code'],
    isFeatured: false,
    screenshotsFolder: 'yasas.dev',
    shortDescription: 'Professional portfolio for material physics researcher, software developer, and SaaS builder.',
    fullDescription: `Professional portfolio website for Sajana Yasas, a material physics researcher, software developer, and SaaS builder.

The platform showcases his work in SaaS and product development, including SyncSEO, startup mentorship with FoundersPath, and digital marketing services through IDER Solutions.`,
    keyFeatures: [
      'Clean, modern developer portfolio design',
      'Project showcase section',
      'Professional background and skills',
      'Contact and connection points',
    ],
    servicesDelivered: [
      'Personal portfolio website development',
      'Modern, minimal design implementation',
      'Responsive design',
    ],
  },
];
